list = [2, 2, 4, 5, 97, 53, 67, 15]
# print(list)
# list.sort()
# print(list)
# list.reverse()
# list.append(76)
# list.insert(3 , 65)
# list.pop(2)
# list.remove(67)
# l=list.count(2)
# print(l)
# l=list.copy()
# l.sort()
# print(l)
# print(list)
